name: Remote Dispatch Action Responder
on: [repository_dispatch, workflow_dispatch]
jobs:
  ping-pong:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        path: content
    - name: ping
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "amar@djinndream.me"
        git clone https://github.com/amarshavir/content
        git add .
        git commit -m "content update"
        echo "Latest Content added"
     
