name: Remote Dispatch Action Responder
on: [repository_dispatch, workflow_dispatch]
jobs:
  ping-pong:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update submodule
      run: git submodule update --init --recursive
    - name: Commit and push changes
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update submodule
          git push
