name: Remote Dispatch Action Responder
on: [repository_dispatch, workflow_dispatch]
jobs:
  ping-pong:

    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: git submodule update --remote --merge && echo "Submodule Update <3"
     
