name: Remote Dispatch Action Responder
on: [repository_dispatch, workflow_dispatch]
jobs:
  ping-pong:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: ping
      run: |
        git --version
        git submodule update --remote --merge
        git config user.name "GitHub Actions Bot"
        git config user.email "amar@djinndream.me"
        echo "Submodule Update <3"
     
